---
name: Ansible Lint
on: [push]
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Ansible Lint
        run: |
          sudo apt-get -y install ansible-lint
          pwd
          ls -la
          ansible-lint -v
